version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - dbProjectEndCourse:/data/db

  minio:
    image: minio/minio
    volumes:
      - ./UploadFilesMinios:/data
    ports:
      - '9000:9000'
      - '6800:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
volumes:
  dbProjectEndCourse:
